import type { AchievementTier } from '@/features/achievements/model/sightingAchievement'

export const mammalAchievementTiers = {
  aardvark: 'legendary',
  aardwolf: 'legendary',
  'african-civet': 'rare',
  'african-clawless-otter': 'legendary',
  'african-lion': 'notable',
  'african-elephant': 'standard',
  'african-buffalo': 'standard',
  'black-rhinoceros': 'legendary',
  'brown-hyena': 'legendary',
  bushpig: 'legendary',
  'lesser-bushbaby': 'notable',
  'thick-tailed-bushbaby': 'notable',
  caracal: 'legendary',
  'chacma-baboon': 'standard',
  cheetah: 'notable',
  eland: 'notable',
  'four-toed-elephant-shrew': 'notable',
  'rock-elephant-shrew': 'notable',
  'short-snouted-elephant-shrew': 'notable',
  'bat-eared-fox': 'legendary',
  'large-spotted-genet': 'notable',
  'small-spotted-genet': 'notable',
  'sharpes-grysbok': 'notable',
  'greater-kudu': 'standard',
  giraffe: 'standard',
  'honey-badger': 'rare',
  'lichtensteins-hartebeest': 'notable',
  'southern-african-hedgehog': 'rare',
  'rock-hyrax': 'notable',
  'yellow-spotted-rock-hyrax': 'notable',
  'side-striped-jackal': 'notable',
  klipspringer: 'notable',
  impala: 'standard',
  leopard: 'notable',
  'large-grey-mongoose': 'notable',
  'water-mongoose': 'notable',
  'mellers-mongoose': 'rare',
  'selous-mongoose': 'rare',
  'white-tailed-mongoose': 'rare',
  'samango-monkey': 'rare',
  nyala: 'standard',
  oribi: 'legendary',
  pangolin: 'legendary',
  'striped-polecat': 'rare',
  porcupine: 'rare',
  'mountain-reedbuck': 'legendary',
  'southern-reedbuck': 'notable',
  'grey-rhebok': 'legendary',
  'red-duiker': 'rare',
  'roan-antelope': 'rare',
  'sable-antelope': 'notable',
  serval: 'legendary',
  'south-african-springhare': 'notable',
  'southern-bushbuck': 'standard',
  'spotted-hyena': 'standard',
  steenbok: 'standard',
  'suni-livingstones': 'rare',
  tsessebe: 'notable',
  'vervet-monkey': 'standard',
  warthog: 'standard',
  waterbuck: 'standard',
  'african-wild-dog': 'notable',
  'african-wild-cat': 'rare',
  'white-rhinoceros': 'rare',
  zebra: 'standard',
} as const satisfies Readonly<Record<string, AchievementTier>>

export function getSightingAchievementTier(animalId: string): AchievementTier {
  return mammalAchievementTiers[animalId as keyof typeof mammalAchievementTiers] ?? 'standard'
}
