import {useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import heroImage from '@/assets/onboarding/park-selection-lion.webp'
import {SponsorFooter} from '@/components/SponsorFooter/SponsorFooter'
import {InformationDisclaimer} from '@/features/information/components/InformationDisclaimer'
import {InformationIcon} from '@/features/information/components/InformationIcon'
import {camps,categories,emergencyContacts,gateTimes,history,rules,serviceTimes,tips as safariTips} from '@/features/information/data/parkInformationData'
import {MammalsBottomNav} from '@/features/mammals/components/MammalsBottomNav/MammalsBottomNav'
import {AddSightingLauncher} from '@/features/sightings/components/AddSightingLauncher/AddSightingLauncher'
import styles from './ParkInformationPage.module.css'

export function ParkInformationPage(){const [query,setQuery]=useState('');const month=new Date().getMonth();const visibleCamps=useMemo(()=>{const term=query.trim().toLowerCase();return term?camps.filter(c=>[c.name,...c.facilities].join(' ').toLowerCase().includes(term)):camps},[query]);return <main className={styles.page}>
 <header className={styles.hero} style={{backgroundImage:`linear-gradient(180deg,rgb(30 51 40/.18),rgb(30 51 40/.88)),url(${heroImage})`}}><Link aria-label="Back to Kruger Home" className={styles.back} to="/parks/kruger"><span/></Link><div><p>Kruger National Park</p><h1>Park Information</h1><InformationDisclaimer compact/></div></header>
 <div className={styles.content}><label className={styles.search}><span>Search park information</span><input onChange={e=>setQuery(e.target.value)} placeholder="Search camps, facilities, rules or tips" type="search" value={query}/>{query?<button onClick={()=>setQuery('')} type="button">Clear</button>:null}</label>
 <nav aria-label="Quick access" className={styles.quick}>{categories.map(category=><a href={`#${category.id}`} key={category.id}><InformationIcon name={category.id}/><span>{category.title}</span></a>)}</nav>
 {query&&visibleCamps.length===0&&!rules.some(r=>(r.title+r.description).toLowerCase().includes(query.toLowerCase()))&&!safariTips.some(t=>(t.title+t.description).toLowerCase().includes(query.toLowerCase()))?<p className={styles.noResults} role="status">No park information matches “{query}”. <button onClick={()=>setQuery('')}>Clear search</button></p>:null}
 <section className={styles.section} id="today"><Heading eyebrow="Plan today" title="Today & Gate Times"/><div className={styles.gateGrid}>{gateTimes.map(t=><article className={t.month===month?styles.currentMonth:''} key={t.monthName}><h3>{t.monthName}{t.month===month?<span>Current</span>:null}</h3><dl><div><dt>Park gates</dt><dd>{t.parkOpen} - {t.parkClose}</dd></div><div><dt>Camp gates</dt><dd>{t.campOpen} - {t.campClose}</dd></div></dl></article>)}</div><div className={styles.hours}><article><h3>Restaurant times</h3>{serviceTimes.restaurant.map(s=><p key={s.label}><span>{s.label}</span><strong>{s.open} - {s.close}</strong></p>)}</article><article><h3>Shop times</h3><p><span>Open</span><strong>{serviceTimes.shop.open} - {serviceTimes.shop.close}</strong></p></article></div><InformationDisclaimer/></section>
 <section className={styles.section} id="driving"><Heading eyebrow="On the road" title="Driving in Kruger"/><div className={styles.editorial}><p>Travel slowly and choose shorter drives. Stop at dams, lookout points and hides rather than trying to cover excessive distance.</p><p>Plan enough time to return before gates close. Fuel is available at larger rest camps, but the source does not identify each fuel point.</p></div><aside className={styles.future}><strong>Distance planner</strong><span>The source chart cannot be reproduced confidently from the scanned document. A verified calculator is deferred.</span></aside></section>
 <section className={styles.section} id="camps"><Heading eyebrow="Practical stops" title="Camps & Facilities"/><label className={styles.campSearch}><span>Find a supported camp or facility</span><input onChange={e=>setQuery(e.target.value)} type="search" value={query}/></label><div className={styles.camps}>{visibleCamps.map(camp=><article key={camp.id}><h3>{camp.name}</h3><ul>{camp.facilities.map(f=><li key={f}>{f}</li>)}</ul>{camp.telephone?<a aria-label={`Call ${camp.name} shop at ${camp.telephone}`} href={`tel:+27${camp.telephone.replace(/\D/g,'').slice(1)}`}>Call shop: {camp.telephone}</a>:null}<small>{camp.notes}</small></article>)}</div></section>
 <section className={styles.emergency} id="emergency"><Heading eyebrow="Keep accessible" title="Emergency"/><p>Mobile coverage may vary. Tap a clearly labelled number only when you intend to call.</p><div>{emergencyContacts.map(contact=><article key={contact.id}><InformationIcon name="emergency"/><span><strong>{contact.service}</strong>{contact.availability?<small>{contact.availability}</small>:null}</span><a aria-label={`Call ${contact.service} at ${contact.number}`} href={`tel:+27${contact.number.replace(/\D/g,'').slice(1)}`}>Call {contact.number}</a></article>)}</div><InformationDisclaimer/></section>
 <section className={styles.section} id="health"><Heading eyebrow="Visitor preparation" title="Health & Safety"/><div className={styles.health}><article><h3>Malaria awareness</h3><p>The source identifies Kruger as a malaria area. Reduce mosquito bites by covering exposed skin and using mosquito repellent, especially between dusk and dawn.</p></article><article><h3>Prepare for the climate</h3><p>The source checklist recommends sunscreen, a sun hat, mosquito repellent, water or refreshments, binoculars and wildlife reference material.</p></article></div><p className={styles.medical}>Seek professional medical help if you become unwell during or after your visit.</p><InformationDisclaimer/></section>
 <section className={styles.section} id="rules"><Heading eyebrow="Travel responsibly" title="Park Rules"/><div className={styles.rules}>{rules.filter(r=>!query||(r.title+r.description).toLowerCase().includes(query.toLowerCase())).map(rule=><article key={rule.id}><InformationIcon name="rules"/><h3>{rule.title}</h3><p>{rule.description}</p></article>)}</div><InformationDisclaimer/></section>
 <section className={styles.section} id="tips"><Heading eyebrow="Field notes" title="Safari Tips"/><div className={styles.tips}>{safariTips.filter(t=>!query||(t.title+t.description).toLowerCase().includes(query.toLowerCase())).map((tip,index)=><article key={tip.id}><span>0{index+1}</span><h3>{tip.title}</h3><p>{tip.description}</p></article>)}</div></section>
 <section className={styles.section} id="about"><Heading eyebrow="A conservation story" title="About Kruger"/><p className={styles.intro}>The source describes Kruger as a major game park recognised for nature conservation, professional wildlife management and safeguarding African cultural heritage.</p><ol className={styles.timeline}>{history.map(item=><li key={item.year}><time>{item.year}</time><div><h3>{item.title}</h3><p>{item.description}</p></div></li>)}</ol></section>
 <footer className={styles.footer}><InformationDisclaimer/><SponsorFooter tone="light"/></footer></div><AddSightingLauncher/><MammalsBottomNav active="information"/></main>}
function Heading({eyebrow,title}:{eyebrow:string;title:string}){return <div className={styles.heading}><p>{eyebrow}</p><h2>{title}</h2></div>}
export function ParkInformationErrorPage(){return <main className={styles.errorPage}><h1>Park Information is unavailable</h1><p>The local visitor information could not be displayed. No data was sent or changed.</p><Link to="/parks/kruger">Return to Kruger Home</Link><MammalsBottomNav active="information"/></main>}
